"""initial tables

Revision ID: 092a2fafedd7
Revises: 
Create Date: 2026-06-24 18:56:18.344703
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '092a2fafedd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('return_reasons',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('return_materials',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lot_ref', sa.String(length=100), nullable=False),
    sa.Column('qty', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('reason_id', sa.BigInteger(), nullable=False),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'processed', name='return_status'), nullable=False),
    sa.Column('destination', sa.Enum('stock', 'scrap', name='return_destination'), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['reason_id'], ['return_reasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_materials_lot_ref'), 'return_materials', ['lot_ref'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['return_id'], ['return_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('return_attachments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('return_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['return_id'], ['return_materials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('return_attachments')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_return_materials_lot_ref'), table_name='return_materials')
    op.drop_table('return_materials')
    op.drop_table('return_reasons')
    # ### end Alembic commands ###
